// ──────────────────────────────────────
// Common Error Codes
// ──────────────────────────────────────

export const ERROR_CODES = {
    // Auth
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
    INVALID_ADMIN_CODE: "INVALID_ADMIN_CODE",
    INVALID_TOKEN: "INVALID_TOKEN",
    TOKEN_EXPIRED: "TOKEN_EXPIRED",

    // Authorization
    UNAUTHORIZED: "UNAUTHORIZED",
    FORBIDDEN: "FORBIDDEN",

    // Resources
    NOT_FOUND: "NOT_FOUND",
    VALIDATION_ERROR: "VALIDATION_ERROR",

    // Test
    TEST_NOT_PUBLISHED: "TEST_NOT_PUBLISHED",
    ATTEMPT_ALREADY_EXISTS: "ATTEMPT_ALREADY_EXISTS",
    ATTEMPT_ALREADY_SUBMITTED: "ATTEMPT_ALREADY_SUBMITTED",
    TEST_TIME_EXPIRED: "TEST_TIME_EXPIRED",

    // General
    INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;